site_name: Notes
site_url: https://fedcba499.github.io/notes/
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - Home: index.md


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
