name: Deploy MkDocs

on:
  push:
    branches:
      - main  # or master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs and Material theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build and Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
